# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: destroyed-symlinks
      - id: detect-private-key

  - repo: https://github.com/ansible/ansible-lint.git
    rev: v5.0.0
    hooks:
      - id: ansible-lint
        always_run: false
        pass_filenames: true
        files: \.(yaml|yml)$
        # yamllint disable-line rule:line-length
        entry: env ANSIBLE_LIBRARY=./plugins/modules ANSIBLE_MODULE_UTILS=./plugins/module_utils ansible-lint --force-color

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.0
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8

  - repo: https://github.com/thlorenz/doctoc
    rev: v2.0.0
    hooks:
      - id: doctoc
        args: [ '--github' ]

  - repo: https://github.com/kadrach/pre-commit-gitlabci-lint
    rev: 1baf80b1130b99bf45db64c7f9d2b1af19ab5662
    hooks:
      - id: gitlabci-lint
        args: ["https://gitlab.com"]

  - repo: https://github.com/robertdebock/pre-commit
    rev: v1.1.2
    hooks:
      - id: ansible_role_find_unused_variable
      - id: ansible_role_find_empty_files
