---
#
# This workflow requires a GALAXY_API_KEY secret present in the GitHub
# repository or organization.
#
name: Publish Role into Galaxy
on:
  push:
    tags:
      - "*"
jobs:
  release:
    name: Publish Role into Galaxy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Ansible
        run: pip3 install ansible-base
      - name: Trigger a new import on Galaxy.
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} $(echo $GITHUB_REPOSITORY | cut -d/ -f1) $(echo $GITHUB_REPOSITORY | cut -d/ -f2)
